const productsData = {
    
    // --- APPAREL CATEGORY (Updated with size-based pricing) ---
    "apparel-men-001": { category: "apparel", title: "Men's Executive Polo", price: 50.00, sizes: { small: 50.00, medium: 52.00, large: 55.00 }, shortDesc: "A classic polo for a sharp, professional look.", longDesc: "Crafted from breathable pique cotton...", rating: "★★★★☆", colors: [{ name: "Charcoal Grey", image: "Images/product6.jpg", thumbnail: "Images/product6.jpg" }], reviewData: [{ author: "David K.", rating: 4, date: "June 23, 2025", text: "Solid polo shirt." }] },
    "apparel-men-002": { category: "apparel", title: "Men's Softshell Jacket", price: 95.00, sizes: { small: 95.00, medium: 98.00, large: 102.00 }, shortDesc: "A versatile and weather-resistant jacket for all seasons.", longDesc: "Our men's softshell jacket provides protection...", rating: "★★★★★", colors: [{ name: "Black", image: "Images/product5.png", thumbnail: "Images/product5.png" }], reviewData: [{ author: "Alex R.", rating: 5, date: "June 22, 2025", text: "Excellent jacket." }] },
    "apparel-men-003": { category: "apparel", title: "Men's Wrinkle-Free Dress Shirt", price: 75.00, sizes: { small: 75.00, medium: 77.00, large: 80.00 }, shortDesc: "A sharp, professional dress shirt that stays crisp all day.", longDesc: "Made with a premium cotton blend, this dress shirt offers a comfortable fit and requires minimal ironing...", rating: "★★★★★", colors: [{ name: "White", image: "Images/product18.jpeg", thumbnail: "Images/product18.jpeg" }], reviewData: [{ author: "Samuel B.", rating: 5, date: "June 18, 2025", text: "Finally, a dress shirt that looks good out of the suitcase." }] },
    "apparel-men-004": { category: "apparel", title: "Custom Corporate Tie", price: 40.00, shortDesc: "A silk tie that can be customized with your company's logo or colors.", longDesc: "Elevate your team's uniform with a custom-designed silk tie...", rating: "★★★★☆", colors: [{ name: "Custom", image: "Images/product17.png", thumbnail: "Images/product17.png" }], reviewData: [{ author: "Richards Co.", rating: 4, date: "June 15, 2025", text: "The ties were a big hit at our conference." }] },
    "apparel-men-005": { category: "apparel", title: "Branded Performance Quarter-Zip", price: 65.00, sizes: { small: 65.00, medium: 68.00, large: 70.00 }, shortDesc: "A lightweight, athletic quarter-zip for active professionals.", longDesc: "Ideal for a morning run or a casual office day, this performance quarter-zip is made from moisture-wicking fabric...", rating: "★★★★★", colors: [{ name: "Heather Grey", image: "Images/product22.png", thumbnail: "Images/product22.png" }], reviewData: [{ author: "Kevin L.", rating: 5, date: "June 12, 2025", text: "My new favorite pullover." }] },
    "apparel-women-001": { category: "apparel", title: "Women's Business Blouse", price: 55.00, sizes: { small: 55.00, medium: 57.00, large: 60.00 }, shortDesc: "An elegant and comfortable blouse for the modern professional.", longDesc: "This business blouse is made from a soft, easy-care fabric...", rating: "★★★★☆", colors: [{ name: "Ivory", image: "Images/product7.jpg", thumbnail: "Images/product7.jpg" }], reviewData: [{ author: "Maria G.", rating: 4, date: "June 21, 2025", text: "Lovely blouse, fits perfectly." }] },
    "apparel-women-002": { category: "apparel", title: "Custom Logo Cardigan", price: 70.00, sizes: { small: 70.00, medium: 73.00, large: 75.00 }, shortDesc: "A soft, fine-knit cardigan perfect for office layering.", longDesc: "This elegant cardigan is a versatile addition to any professional wardrobe...", rating: "★★★★☆", colors: [{ name: "Beige", image: "Images/product19.png", thumbnail: "Images/product19.png" }], reviewData: [{ author: "Jessica M.", rating: 4, date: "June 02, 2025", text: "Very soft and professional." }] },
    "apparel-women-003": { category: "apparel", title: "Tailored Corporate Blazer", price: 150.00, sizes: { small: 150.00, medium: 155.00, large: 160.00 }, shortDesc: "A modern, tailored blazer that exudes professionalism.", longDesc: "Our corporate blazer is designed with a modern, flattering silhouette...", rating: "★★★★★", colors: [{ name: "Navy", image: "Images/product20.png", thumbnail: "Images/product20.png" }], reviewData: [{ author: "Chloe S.", rating: 5, date: "May 28, 2025", text: "This blazer is stunning." }] },
    "apparel-women-004": { category: "apparel", title: "Branded Yoga Pants", price: 60.00, sizes: { small: 60.00, medium: 62.00, large: 65.00 }, shortDesc: "High-quality, comfortable yoga pants for corporate wellness programs.", longDesc: "Promote well-being with these premium, high-waisted yoga pants...", rating: "★★★★★", colors: [{ name: "Black", image: "Images/product21.png", thumbnail: "Images/product21.png" }], reviewData: [{ author: "Wellness Inc.", rating: 5, date: "May 10, 2025", text: "Our employees loved these as a wellness gift." }] },
    "apparel-kids-001": { category: "apparel", title: "Kids' Team T-Shirt", price: 20.00, sizes: { small: 20.00, medium: 21.00, large: 22.00 }, shortDesc: "A soft and durable 100% cotton t-shirt for kids.", longDesc: "Perfect for school events, sports teams, or family gatherings...", rating: "★★★★★", colors: [{ name: "Royal Blue", image: "Images/product8.png", thumbnail: "Images/product8.png" }], reviewData: [{ author: "Sarah P.", rating: 5, date: "June 20, 2025", text: "The kids loved their team shirts!" }] },
    "apparel-kids-002": { category: "apparel", title: "Youth Sports Cap", price: 18.00, shortDesc: "A comfortable and stylish cap for young team members.", longDesc: "This youth-sized cap features a classic design...", rating: "★★★★☆", colors: [{ name: "Red", image: "Images/product10.jpg", thumbnail: "Images/product10.jpg" }], reviewData: [{ author: "Tom F.", rating: 4, date: "June 19, 2025", text: "Good quality caps." }] },
    "apparel-kids-003": { category: "apparel", title: "Children's Hooded Sweatshirt", price: 45.00, sizes: { small: 45.00, medium: 47.00, large: 49.00 }, shortDesc: "A cozy and warm hoodie for school teams or events.", longDesc: "Keep the little ones warm with this soft, fleece-lined hooded sweatshirt...", rating: "★★★★★", colors: [{ name: "Heather Grey", image: "Images/product23.jpeg", thumbnail: "Images/product23.jpeg" }], reviewData: [{ author: "PTA Board", rating: 5, date: "April 15, 2025", text: "Perfect for our school's spirit wear." }] },
    "apparel-kids-004": { category: "apparel", title: "Youth Drawstring Bag", price: 15.00, shortDesc: "A lightweight and durable bag for sports or day trips.", longDesc: "This simple and effective drawstring bag is perfect for carrying sports gear...", rating: "★★★★☆", colors: [{ name: "Green", image: "Images/product24.png", thumbnail: "Images/product24.png" }], reviewData: [{ author: "Coach Dave", rating: 4, date: "April 05, 2025", text: "Great, affordable bags for the whole team." }] },
    
    // --- SPICES CATEGORY ---
    "spice-box-002": { category: "spice", title: "Artisan Spice Box", price: 95.00, shortDesc: "An exquisitely curated collection of authentic Middle Eastern spices.", longDesc: "Embark on a culinary journey...", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product2.png", thumbnail: "Images/product2.png" }], reviewData: [{ author: "Yusuf K.", rating: 5, date: "June 21, 2025", text: "A fantastic collection." }] },
    "spice-002": { category: "spice", title: "Premium Saffron Threads", price: 35.00, shortDesc: "Grade A, pure saffron threads.", longDesc: "Sourced from the finest crocus flowers...", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product9.jpg", thumbnail: "Images/product9.jpg" }], reviewData: [{ author: "Isabella V.", rating: 5, date: "June 01, 2025", text: "Incredible aroma and color." }] },
    "spice-003": { category: "spice", title: "Smoked Spanish Paprika", price: 15.00, shortDesc: "Authentic Pimentón de la Vera with a rich, smoky flavor.", longDesc: "Add a deep, smoky dimension to your dishes...", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product13.png", thumbnail: "Images/product13.png" }], reviewData: [{ author: "Liam G.", rating: 5, date: "May 25, 2025", text: "Deep, rich smoky flavor. Excellent product." }] },
    "spice-004": { category: "spice", title: "Exotic Za'atar Blend", price: 20.00, shortDesc: "A classic Middle Eastern spice blend of thyme, sesame seeds, and sumac.", longDesc: "Our traditional Za'atar blend is a versatile and aromatic seasoning...", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product14.jpg", thumbnail: "Images/product14.jpg" }], reviewData: [{ author: "Aisha B.", rating: 5, date: "June 14, 2025", text: "Perfectly balanced and so fresh." }] },
    "spice-005": { category: "spice", title: "Gourmet Vanilla Beans", price: 25.00, shortDesc: "Plump, Grade A vanilla beans from Madagascar.", longDesc: "Unleash true vanilla flavor in your baking and desserts with these fragrant, high-quality vanilla beans, bursting with thousands of tiny seeds.", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product15.png", thumbnail: "Images/product15.png" }], reviewData: [{ author: "PastryChef", rating: 5, date: "June 24, 2025", text: "The best vanilla beans I've used. So aromatic." }] },
    "spice-006": { category: "spice", title: "Sumac Spice", price: 12.00, shortDesc: "A tangy, lemony spice popular in Mediterranean and Middle Eastern cooking.", longDesc: "Our ground sumac offers a bright, acidic flavor that can liven up salads, grilled meats, and dips. It's a versatile essential for any adventurous cook.", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product16.png", thumbnail: "Images/product16.png" }], reviewData: [{ author: "Hassan T.", rating: 4, date: "June 23, 2025", text: "Good quality sumac, very tangy." }] },

    // --- PERFUMES CATEGORY ---
    "oud-perfume-003": { category: "perfume", title: "Luxury Oud Perfume", price: 250.00, shortDesc: "A captivating and long-lasting fragrance.", longDesc: "Immerse yourself in the captivating allure...", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product3.png", thumbnail: "Images/product3.png" }], reviewData: [{ author: "Noora S.", rating: 5, date: "June 22, 2025", text: "The most exquisite oud." }] },
    "perfume-002": { category: "perfume", title: "Amber Noir Eau de Parfum", price: 180.00, shortDesc: "A warm and mysterious fragrance.", longDesc: "Amber Noir is a seductive and alluring scent...", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product11.png", thumbnail: "Images/product11.png" }], reviewData: [{ author: "Sophia L.", rating: 5, date: "May 30, 2025", text: "This scent is absolutely intoxicating." }] },
    "perfume-003": { category: "perfume", title: "Santal Royale", price: 220.00, shortDesc: "An elegant and woody fragrance centered around rich sandalwood.", longDesc: "Santal Royale is a tribute to the noble and creamy scent of sandalwood...", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product27.png", thumbnail: "Images/product27.png" }], reviewData: [{ author: "Ava C.", rating: 5, date: "June 08, 2025", text: "A true, creamy sandalwood scent." }] },
    "perfume-004": { category: "perfume", title: "White Musk Perfume Oil", price: 90.00, shortDesc: "A clean, soft, and sensual concentrated perfume oil.", longDesc: "Experience the subtle allure of White Musk...", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product28.png", thumbnail: "Images/product28.png" }], reviewData: [{ author: "Jessica P.", rating: 5, date: "June 11, 2025", text: "A 'your skin but better' scent." }] },
    "perfume-005": { category: "perfume", title: "Rose & Saffron Elixir", price: 195.00, shortDesc: "A romantic and exotic blend of floral rose and spicy saffron.", longDesc: "This unique fragrance combines the timeless romance of rose petals with the luxurious, warm spice of saffron, creating a truly memorable and sophisticated aroma.", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product29.png", thumbnail: "Images/product29.png" }], reviewData: [{ author: "Anonymous", rating: 5, date: "June 05, 2025", text: "A beautiful and unique combination." }] },
    "perfume-006": { category: "perfume", title: "Citrus Grove", price: 160.00, shortDesc: "A fresh and vibrant citrus scent for daily wear.", longDesc: "Awaken your senses with Citrus Grove, a bright and zesty fragrance bursting with notes of Italian lemon, bergamot, and a hint of fresh basil.", rating: "★★★★☆", colors: [{ name: "Default", image: "Images/product30.png", thumbnail: "Images/product30.png" }], reviewData: [{ author: "Mark R.", rating: 4, date: "May 20, 2025", text: "Very fresh and clean. Perfect for summer." }] },
    
    // --- GIFTS CATEGORY ---
    "pen-set-004": { category: "gift", title: "Custom Engraved Pen Set", price: 75.00, shortDesc: "A sleek and professional pen set.", longDesc: "Make a statement with our Custom Engraved Pen Set...", rating: "★★★★☆", colors: [{ name: "Black", image: "Images/product4.png", thumbnail: "Images/product4.png" }], reviewData: [{ author: "Sarah I.", rating: 5, date: "June 17, 2025", text: "The custom engraving was perfect." }] },
    "gift-002": { category: "gift", title: "Engraved Leather Journal", price: 55.00, shortDesc: "A high-quality leather-bound journal.", longDesc: "This beautiful journal features a soft, genuine leather cover...", rating: "★★★★★", colors: [{ name: "Brown", image: "Images/product12.png", thumbnail: "Images/product12.png" }], reviewData: [{ author: "Olivia W.", rating: 5, date: "April 28, 2025", text: "The leather is soft and the engraving was flawless." }] },
    "gift-004": { category: "gift", title: "Gourmet Gift Hamper", price: 150.00, shortDesc: "A curated hamper of gourmet treats, customizable for any corporate occasion.", longDesc: "Delight clients and employees with a luxurious hamper filled with a selection of fine cheeses, artisanal crackers, premium chocolates, and other gourmet delights...", rating: "★★★★★", colors: [{ name: "Default", image: "Images/product26.png", thumbnail: "Images/product26.png" }], reviewData: [{ author: "Grace Lee", rating: 5, date: "June 18, 2025", text: "Sent this to a client and they were blown away." }] },
    "gift-005": { category: "gift", title: "Elegant Silk Scarf", price: 120.00, shortDesc: "A luxurious silk scarf with intricate patterns.", longDesc: "Discover the exquisite craftsmanship of our Elegant Silk Scarf...", rating: "★★★★☆", colors: [{ name: "Red", image: "Images/product1.png", thumbnail: "Images/product1.png" }], reviewData: [{ author: "Fatima A.", rating: 5, date: "June 20, 2025", text: "Absolutely stunning!" }] },
    "gift-006": { category: "gift", title: "Branded Wireless Charger", price: 80.00, shortDesc: "A sleek, fast-charging wireless pad with your company logo.", longDesc: "A practical and modern gift, this Qi-certified wireless charging pad offers convenience and style. Your logo is printed in high-resolution, keeping your brand top-of-mind on any desk.", rating: "★★★★☆", colors: [{ name: "White", image: "Images/product25.png", thumbnail: "Images/product25.png" }], reviewData: [{ author: "Tech Solutions", rating: 4, date: "March 10, 2025", text: "A very useful and well-received gift for our clients." }] }
};